---
- include_tasks: ../../common/tasks/yunohost_app.yml
  vars:
    app_name: "forgejo"
    app_label: "Forgejo"
    app_args: "domain={{ apps.forgejo.domain }}&path={{ apps.forgejo.path }}&is_public={{ 'true' if apps.forgejo.access == 'public' else 'false' }}&admin_user={{ admin_user }}"
